### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by emargareten** [emargareten/laravel-starting-point#1]
- [ ] Separate Opinionated Commands
- [ ] Clean Up app.js
- [ ] Add Profile Management Tests
- [ ] Add Users Management (for admins)
- [ ] Add Example Resource?
- [ ] Clean Up Inertia Error Handling (use banners/inertia inline etc)

**Comment by emargareten** [comment]
```@apply 'appearance-none text-base leading-normal bg-white border border-primary-400 focus:outline-none focus:ring ring-primary-400 rounded-md placeholder-primary-300 py-2 px-3';```
